/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WebRouteImport } from './routes/web'
import { Route as MobileRouteImport } from './routes/mobile'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WebStaffRouteImport } from './routes/web.staff'
import { Route as WebSettingsRouteImport } from './routes/web.settings'
import { Route as WebReportsRouteImport } from './routes/web.reports'
import { Route as WebReportToManagerRouteImport } from './routes/web.report-to-manager'
import { Route as WebIntegrationsRouteImport } from './routes/web.integrations'
import { Route as WebHospitalsRouteImport } from './routes/web.hospitals'
import { Route as WebGrowthRouteImport } from './routes/web.growth'
import { Route as WebFollowupRouteImport } from './routes/web.followup'
import { Route as WebDashboardRouteImport } from './routes/web.dashboard'
import { Route as WebChildrenRouteImport } from './routes/web.children'
import { Route as WebAuditRouteImport } from './routes/web.audit'
import { Route as WebAssessmentsRouteImport } from './routes/web.assessments'
import { Route as WebAnalyticsRouteImport } from './routes/web.analytics'
import { Route as MobileVisitsRouteImport } from './routes/mobile.visits'
import { Route as MobileSyncRouteImport } from './routes/mobile.sync'
import { Route as MobileRegisterRouteImport } from './routes/mobile.register'
import { Route as MobileNotificationsRouteImport } from './routes/mobile.notifications'
import { Route as MobileMeasureRouteImport } from './routes/mobile.measure'
import { Route as MobileHomeRouteImport } from './routes/mobile.home'
import { Route as MobileChatRouteImport } from './routes/mobile.chat'
import { Route as WebChildrenNewRouteImport } from './routes/web.children.new'
import { Route as WebChildrenChildIdRouteImport } from './routes/web.children.$childId'

const WebRoute = WebRouteImport.update({
  id: '/web',
  path: '/web',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileRoute = MobileRouteImport.update({
  id: '/mobile',
  path: '/mobile',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WebStaffRoute = WebStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => WebRoute,
} as any)
const WebSettingsRoute = WebSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => WebRoute,
} as any)
const WebReportsRoute = WebReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => WebRoute,
} as any)
const WebReportToManagerRoute = WebReportToManagerRouteImport.update({
  id: '/report-to-manager',
  path: '/report-to-manager',
  getParentRoute: () => WebRoute,
} as any)
const WebIntegrationsRoute = WebIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => WebRoute,
} as any)
const WebHospitalsRoute = WebHospitalsRouteImport.update({
  id: '/hospitals',
  path: '/hospitals',
  getParentRoute: () => WebRoute,
} as any)
const WebGrowthRoute = WebGrowthRouteImport.update({
  id: '/growth',
  path: '/growth',
  getParentRoute: () => WebRoute,
} as any)
const WebFollowupRoute = WebFollowupRouteImport.update({
  id: '/followup',
  path: '/followup',
  getParentRoute: () => WebRoute,
} as any)
const WebDashboardRoute = WebDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => WebRoute,
} as any)
const WebChildrenRoute = WebChildrenRouteImport.update({
  id: '/children',
  path: '/children',
  getParentRoute: () => WebRoute,
} as any)
const WebAuditRoute = WebAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => WebRoute,
} as any)
const WebAssessmentsRoute = WebAssessmentsRouteImport.update({
  id: '/assessments',
  path: '/assessments',
  getParentRoute: () => WebRoute,
} as any)
const WebAnalyticsRoute = WebAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => WebRoute,
} as any)
const MobileVisitsRoute = MobileVisitsRouteImport.update({
  id: '/visits',
  path: '/visits',
  getParentRoute: () => MobileRoute,
} as any)
const MobileSyncRoute = MobileSyncRouteImport.update({
  id: '/sync',
  path: '/sync',
  getParentRoute: () => MobileRoute,
} as any)
const MobileRegisterRoute = MobileRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => MobileRoute,
} as any)
const MobileNotificationsRoute = MobileNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => MobileRoute,
} as any)
const MobileMeasureRoute = MobileMeasureRouteImport.update({
  id: '/measure',
  path: '/measure',
  getParentRoute: () => MobileRoute,
} as any)
const MobileHomeRoute = MobileHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => MobileRoute,
} as any)
const MobileChatRoute = MobileChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => MobileRoute,
} as any)
const WebChildrenNewRoute = WebChildrenNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => WebChildrenRoute,
} as any)
const WebChildrenChildIdRoute = WebChildrenChildIdRouteImport.update({
  id: '/$childId',
  path: '/$childId',
  getParentRoute: () => WebChildrenRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mobile': typeof MobileRouteWithChildren
  '/web': typeof WebRouteWithChildren
  '/mobile/chat': typeof MobileChatRoute
  '/mobile/home': typeof MobileHomeRoute
  '/mobile/measure': typeof MobileMeasureRoute
  '/mobile/notifications': typeof MobileNotificationsRoute
  '/mobile/register': typeof MobileRegisterRoute
  '/mobile/sync': typeof MobileSyncRoute
  '/mobile/visits': typeof MobileVisitsRoute
  '/web/analytics': typeof WebAnalyticsRoute
  '/web/assessments': typeof WebAssessmentsRoute
  '/web/audit': typeof WebAuditRoute
  '/web/children': typeof WebChildrenRouteWithChildren
  '/web/dashboard': typeof WebDashboardRoute
  '/web/followup': typeof WebFollowupRoute
  '/web/growth': typeof WebGrowthRoute
  '/web/hospitals': typeof WebHospitalsRoute
  '/web/integrations': typeof WebIntegrationsRoute
  '/web/report-to-manager': typeof WebReportToManagerRoute
  '/web/reports': typeof WebReportsRoute
  '/web/settings': typeof WebSettingsRoute
  '/web/staff': typeof WebStaffRoute
  '/web/children/$childId': typeof WebChildrenChildIdRoute
  '/web/children/new': typeof WebChildrenNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mobile': typeof MobileRouteWithChildren
  '/web': typeof WebRouteWithChildren
  '/mobile/chat': typeof MobileChatRoute
  '/mobile/home': typeof MobileHomeRoute
  '/mobile/measure': typeof MobileMeasureRoute
  '/mobile/notifications': typeof MobileNotificationsRoute
  '/mobile/register': typeof MobileRegisterRoute
  '/mobile/sync': typeof MobileSyncRoute
  '/mobile/visits': typeof MobileVisitsRoute
  '/web/analytics': typeof WebAnalyticsRoute
  '/web/assessments': typeof WebAssessmentsRoute
  '/web/audit': typeof WebAuditRoute
  '/web/children': typeof WebChildrenRouteWithChildren
  '/web/dashboard': typeof WebDashboardRoute
  '/web/followup': typeof WebFollowupRoute
  '/web/growth': typeof WebGrowthRoute
  '/web/hospitals': typeof WebHospitalsRoute
  '/web/integrations': typeof WebIntegrationsRoute
  '/web/report-to-manager': typeof WebReportToManagerRoute
  '/web/reports': typeof WebReportsRoute
  '/web/settings': typeof WebSettingsRoute
  '/web/staff': typeof WebStaffRoute
  '/web/children/$childId': typeof WebChildrenChildIdRoute
  '/web/children/new': typeof WebChildrenNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/mobile': typeof MobileRouteWithChildren
  '/web': typeof WebRouteWithChildren
  '/mobile/chat': typeof MobileChatRoute
  '/mobile/home': typeof MobileHomeRoute
  '/mobile/measure': typeof MobileMeasureRoute
  '/mobile/notifications': typeof MobileNotificationsRoute
  '/mobile/register': typeof MobileRegisterRoute
  '/mobile/sync': typeof MobileSyncRoute
  '/mobile/visits': typeof MobileVisitsRoute
  '/web/analytics': typeof WebAnalyticsRoute
  '/web/assessments': typeof WebAssessmentsRoute
  '/web/audit': typeof WebAuditRoute
  '/web/children': typeof WebChildrenRouteWithChildren
  '/web/dashboard': typeof WebDashboardRoute
  '/web/followup': typeof WebFollowupRoute
  '/web/growth': typeof WebGrowthRoute
  '/web/hospitals': typeof WebHospitalsRoute
  '/web/integrations': typeof WebIntegrationsRoute
  '/web/report-to-manager': typeof WebReportToManagerRoute
  '/web/reports': typeof WebReportsRoute
  '/web/settings': typeof WebSettingsRoute
  '/web/staff': typeof WebStaffRoute
  '/web/children/$childId': typeof WebChildrenChildIdRoute
  '/web/children/new': typeof WebChildrenNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/mobile'
    | '/web'
    | '/mobile/chat'
    | '/mobile/home'
    | '/mobile/measure'
    | '/mobile/notifications'
    | '/mobile/register'
    | '/mobile/sync'
    | '/mobile/visits'
    | '/web/analytics'
    | '/web/assessments'
    | '/web/audit'
    | '/web/children'
    | '/web/dashboard'
    | '/web/followup'
    | '/web/growth'
    | '/web/hospitals'
    | '/web/integrations'
    | '/web/report-to-manager'
    | '/web/reports'
    | '/web/settings'
    | '/web/staff'
    | '/web/children/$childId'
    | '/web/children/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/mobile'
    | '/web'
    | '/mobile/chat'
    | '/mobile/home'
    | '/mobile/measure'
    | '/mobile/notifications'
    | '/mobile/register'
    | '/mobile/sync'
    | '/mobile/visits'
    | '/web/analytics'
    | '/web/assessments'
    | '/web/audit'
    | '/web/children'
    | '/web/dashboard'
    | '/web/followup'
    | '/web/growth'
    | '/web/hospitals'
    | '/web/integrations'
    | '/web/report-to-manager'
    | '/web/reports'
    | '/web/settings'
    | '/web/staff'
    | '/web/children/$childId'
    | '/web/children/new'
  id:
    | '__root__'
    | '/'
    | '/mobile'
    | '/web'
    | '/mobile/chat'
    | '/mobile/home'
    | '/mobile/measure'
    | '/mobile/notifications'
    | '/mobile/register'
    | '/mobile/sync'
    | '/mobile/visits'
    | '/web/analytics'
    | '/web/assessments'
    | '/web/audit'
    | '/web/children'
    | '/web/dashboard'
    | '/web/followup'
    | '/web/growth'
    | '/web/hospitals'
    | '/web/integrations'
    | '/web/report-to-manager'
    | '/web/reports'
    | '/web/settings'
    | '/web/staff'
    | '/web/children/$childId'
    | '/web/children/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MobileRoute: typeof MobileRouteWithChildren
  WebRoute: typeof WebRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/web': {
      id: '/web'
      path: '/web'
      fullPath: '/web'
      preLoaderRoute: typeof WebRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile': {
      id: '/mobile'
      path: '/mobile'
      fullPath: '/mobile'
      preLoaderRoute: typeof MobileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/web/staff': {
      id: '/web/staff'
      path: '/staff'
      fullPath: '/web/staff'
      preLoaderRoute: typeof WebStaffRouteImport
      parentRoute: typeof WebRoute
    }
    '/web/settings': {
      id: '/web/settings'
      path: '/settings'
      fullPath: '/web/settings'
      preLoaderRoute: typeof WebSettingsRouteImport
      parentRoute: typeof WebRoute
    }
    '/web/reports': {
      id: '/web/reports'
      path: '/reports'
      fullPath: '/web/reports'
      preLoaderRoute: typeof WebReportsRouteImport
      parentRoute: typeof WebRoute
    }
    '/web/report-to-manager': {
      id: '/web/report-to-manager'
      path: '/report-to-manager'
      fullPath: '/web/report-to-manager'
      preLoaderRoute: typeof WebReportToManagerRouteImport
      parentRoute: typeof WebRoute
    }
    '/web/integrations': {
      id: '/web/integrations'
      path: '/integrations'
      fullPath: '/web/integrations'
      preLoaderRoute: typeof WebIntegrationsRouteImport
      parentRoute: typeof WebRoute
    }
    '/web/hospitals': {
      id: '/web/hospitals'
      path: '/hospitals'
      fullPath: '/web/hospitals'
      preLoaderRoute: typeof WebHospitalsRouteImport
      parentRoute: typeof WebRoute
    }
    '/web/growth': {
      id: '/web/growth'
      path: '/growth'
      fullPath: '/web/growth'
      preLoaderRoute: typeof WebGrowthRouteImport
      parentRoute: typeof WebRoute
    }
    '/web/followup': {
      id: '/web/followup'
      path: '/followup'
      fullPath: '/web/followup'
      preLoaderRoute: typeof WebFollowupRouteImport
      parentRoute: typeof WebRoute
    }
    '/web/dashboard': {
      id: '/web/dashboard'
      path: '/dashboard'
      fullPath: '/web/dashboard'
      preLoaderRoute: typeof WebDashboardRouteImport
      parentRoute: typeof WebRoute
    }
    '/web/children': {
      id: '/web/children'
      path: '/children'
      fullPath: '/web/children'
      preLoaderRoute: typeof WebChildrenRouteImport
      parentRoute: typeof WebRoute
    }
    '/web/audit': {
      id: '/web/audit'
      path: '/audit'
      fullPath: '/web/audit'
      preLoaderRoute: typeof WebAuditRouteImport
      parentRoute: typeof WebRoute
    }
    '/web/assessments': {
      id: '/web/assessments'
      path: '/assessments'
      fullPath: '/web/assessments'
      preLoaderRoute: typeof WebAssessmentsRouteImport
      parentRoute: typeof WebRoute
    }
    '/web/analytics': {
      id: '/web/analytics'
      path: '/analytics'
      fullPath: '/web/analytics'
      preLoaderRoute: typeof WebAnalyticsRouteImport
      parentRoute: typeof WebRoute
    }
    '/mobile/visits': {
      id: '/mobile/visits'
      path: '/visits'
      fullPath: '/mobile/visits'
      preLoaderRoute: typeof MobileVisitsRouteImport
      parentRoute: typeof MobileRoute
    }
    '/mobile/sync': {
      id: '/mobile/sync'
      path: '/sync'
      fullPath: '/mobile/sync'
      preLoaderRoute: typeof MobileSyncRouteImport
      parentRoute: typeof MobileRoute
    }
    '/mobile/register': {
      id: '/mobile/register'
      path: '/register'
      fullPath: '/mobile/register'
      preLoaderRoute: typeof MobileRegisterRouteImport
      parentRoute: typeof MobileRoute
    }
    '/mobile/notifications': {
      id: '/mobile/notifications'
      path: '/notifications'
      fullPath: '/mobile/notifications'
      preLoaderRoute: typeof MobileNotificationsRouteImport
      parentRoute: typeof MobileRoute
    }
    '/mobile/measure': {
      id: '/mobile/measure'
      path: '/measure'
      fullPath: '/mobile/measure'
      preLoaderRoute: typeof MobileMeasureRouteImport
      parentRoute: typeof MobileRoute
    }
    '/mobile/chat': {
      id: '/mobile/chat'
      path: '/chat'
      fullPath: '/mobile/chat'
      preLoaderRoute: typeof MobileChatRouteImport
      parentRoute: typeof MobileRoute
    }
    '/mobile/home': {
      id: '/mobile/home'
      path: '/home'
      fullPath: '/mobile/home'
      preLoaderRoute: typeof MobileHomeRouteImport
      parentRoute: typeof MobileRoute
    }
    '/web/children/new': {
      id: '/web/children/new'
      path: '/new'
      fullPath: '/web/children/new'
      preLoaderRoute: typeof WebChildrenNewRouteImport
      parentRoute: typeof WebChildrenRoute
    }
    '/web/children/$childId': {
      id: '/web/children/$childId'
      path: '/$childId'
      fullPath: '/web/children/$childId'
      preLoaderRoute: typeof WebChildrenChildIdRouteImport
      parentRoute: typeof WebChildrenRoute
    }
  }
}

interface MobileRouteChildren {
  MobileChatRoute: typeof MobileChatRoute
  MobileHomeRoute: typeof MobileHomeRoute
  MobileMeasureRoute: typeof MobileMeasureRoute
  MobileNotificationsRoute: typeof MobileNotificationsRoute
  MobileRegisterRoute: typeof MobileRegisterRoute
  MobileSyncRoute: typeof MobileSyncRoute
  MobileVisitsRoute: typeof MobileVisitsRoute
}

const MobileRouteChildren: MobileRouteChildren = {
  MobileChatRoute: MobileChatRoute,
  MobileHomeRoute: MobileHomeRoute,
  MobileMeasureRoute: MobileMeasureRoute,
  MobileNotificationsRoute: MobileNotificationsRoute,
  MobileRegisterRoute: MobileRegisterRoute,
  MobileSyncRoute: MobileSyncRoute,
  MobileVisitsRoute: MobileVisitsRoute,
}

const MobileRouteWithChildren =
  MobileRoute._addFileChildren(MobileRouteChildren)

interface WebChildrenRouteChildren {
  WebChildrenChildIdRoute: typeof WebChildrenChildIdRoute
  WebChildrenNewRoute: typeof WebChildrenNewRoute
}

const WebChildrenRouteChildren: WebChildrenRouteChildren = {
  WebChildrenChildIdRoute: WebChildrenChildIdRoute,
  WebChildrenNewRoute: WebChildrenNewRoute,
}

const WebChildrenRouteWithChildren = WebChildrenRoute._addFileChildren(
  WebChildrenRouteChildren,
)

interface WebRouteChildren {
  WebAnalyticsRoute: typeof WebAnalyticsRoute
  WebAssessmentsRoute: typeof WebAssessmentsRoute
  WebAuditRoute: typeof WebAuditRoute
  WebChildrenRoute: typeof WebChildrenRouteWithChildren
  WebDashboardRoute: typeof WebDashboardRoute
  WebFollowupRoute: typeof WebFollowupRoute
  WebGrowthRoute: typeof WebGrowthRoute
  WebHospitalsRoute: typeof WebHospitalsRoute
  WebIntegrationsRoute: typeof WebIntegrationsRoute
  WebReportToManagerRoute: typeof WebReportToManagerRoute
  WebReportsRoute: typeof WebReportsRoute
  WebSettingsRoute: typeof WebSettingsRoute
  WebStaffRoute: typeof WebStaffRoute
}

const WebRouteChildren: WebRouteChildren = {
  WebAnalyticsRoute: WebAnalyticsRoute,
  WebAssessmentsRoute: WebAssessmentsRoute,
  WebAuditRoute: WebAuditRoute,
  WebChildrenRoute: WebChildrenRouteWithChildren,
  WebDashboardRoute: WebDashboardRoute,
  WebFollowupRoute: WebFollowupRoute,
  WebGrowthRoute: WebGrowthRoute,
  WebHospitalsRoute: WebHospitalsRoute,
  WebIntegrationsRoute: WebIntegrationsRoute,
  WebReportToManagerRoute: WebReportToManagerRoute,
  WebReportsRoute: WebReportsRoute,
  WebSettingsRoute: WebSettingsRoute,
  WebStaffRoute: WebStaffRoute,
}

const WebRouteWithChildren = WebRoute._addFileChildren(WebRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MobileRoute: MobileRouteWithChildren,
  WebRoute: WebRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
